spring:
  application:
    name: oauth-authorization-server

server:
  port: 8081
  servlet: 
    context-path: /oauth-authorization-server
  use-forward-headers: false

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  level.org.springframework.security: DEBUG

# http://localhost:8081/oauth-authorization-server/login
